### ISSUE TITLE
The quarantine delay resets with each update to a PR

### ISSUE THREAD

**Issue by joris974** [freckle/mergeabot-action#14]
When a PR is created, the quarantine delay timer starts. However, any subsequent updates to the PR (such as rebasing due to changes in affected files) cause the quarantine delay to reset. This becomes problematic when using mergeabot in conjunction with dependabot, which frequently updates package manager files. As a result, the quarantine delay is perpetually reset, preventing mergeabot from ever merging the PR.
Can mergeabot be configured to use the PR creation time as the reference point for the quarantine delay, rather than resetting it with each update?

**Comment by pbrisbin** [comment]
Originally, it was thought that Dependabot could advance a dependency within the same PR, which would require resetting the clock. Since it would be more complexity to determine if that did or didn't happen, we decided to "fail safe" and reset the clock on any update.

It seems Dependabot will **not** do that. If it's advancing a dependency from where the PR originally was opened, it will close that PR and open a new one (with a "supersedes" comment). That means it should be perfectly safe to measure quarantine from something like `pull_request.opened_at` all the time.
